config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # namespace :admin do
  #     resources :targets
  #     resources :employees
  #     resources :teams
  #     resources :divisions
  #     resources :users
  #     root to: "users#index"
  #   end
  # devise_for :users
  resources :employees
  resources :divisions
  resources :targets
  resources :teams
  resources :users

  # root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/target.rb
class Target < ApplicationRecord
    has_one :Team

    validates :title, presence:true
    validates :description, presence:true
    validates :start_date, presence:true
    validates :team, presence:true
    validates :status, presence:true
    validates :finish_date, presence: true  # date:{ after_or_equal_to: :start_date} ? 

end

app/controllers/admin/targets_controller.rb
# module Admin
#   class TargetsController < Admin::ApplicationController
#     # Overwrite any of the RESTful controller actions to implement custom behavior
#     # For example, you may want to send an email after a foo is updated.
#     #
#     # def update
#     #   super
#     #   send_foo_updated_email(requested_resource)
#     # end

#     # Override this method to specify custom lookup behavior.
#     # This will be used to set the resource for the `show`, `edit`, and `update`
#     # actions.
#     #
#     # def find_resource(param)
#     #   Foo.find_by!(slug: param)
#     # end

#     # The result of this lookup will be available as `requested_resource`

#     # Override this if you have certain roles that require a subset
#     # this will be used to set the records shown on the `index` action.
#     #
#     # def scoped_resource
#     #   if current_user.super_admin?
#     #     resource_class
#     #   else
#     #     resource_class.with_less_stuff
#     #   end
#     # end

#     # Override `resource_params` if you want to transform the submitted
#     # data before it's persisted. For example, the following would turn all
#     # empty values into nil values. It uses other APIs such as `resource_class`
#     # and `dashboard`:
#     #
#     # def resource_params
#     #   params.require(resource_class.model_name.param_key).
#     #     permit(dashboard.permitted_attributes).
#     #     transform_values { |value| value == "" ? nil : value }
#     # end

#     # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
#     # for more information
#   end
# end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: %i[ show edit update destroy ]

  # GET /targets or /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1 or /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets or /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to target_url(@target), notice: "Target was successfully created." }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1 or /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to target_url(@target), notice: "Target was successfully updated." }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1 or /targets/1.json
  def destroy
    @target.destroy

    respond_to do |format|
      format.html { redirect_to targets_url, notice: "Target was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def target_params
      params.require(:target).permit(:title, :description, :start_date, :finish_date, :attribute, :team, :status)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_with(model: target) do |form| %>
  <% if target.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
        <% target.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :finish_date, style: "display: block" %>
    <%= form.date_field :finish_date %>
  </div>

  <div>
    <%= form.label :attribute, style: "display: block" %>
    <%= form.text_field :attribute %>
  </div>

  <div>
    <%= form.label :team, style: "display: block" %>
    <%= form.text_field :team %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/targets/_target.html.erb
<div id="<%= dom_id target %>">
  <p>
    <strong>Title:</strong>
    <%= target.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= target.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= target.start_date %>
  </p>

  <p>
    <strong>Finish date:</strong>
    <%= target.finish_date %>
  </p>

  <p>
    <strong>Attribute:</strong>
    <%= target.attribute %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= target.team %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= target.status %>
  </p>

</div>

app/views/targets/edit.html.erb
<h1>Editing target</h1>

<%= render "form", target: @target %>

<br>

<div>
  <%= link_to "Show this target", @target %> |
  <%= link_to "Back to targets", targets_path %>
</div>

app/views/targets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Targets</h1>

<div id="targets">
  <% @targets.each do |target| %>
    <%= render target %>
    <p>
      <%= link_to "Show this target", target %>
    </p>
  <% end %>
</div>

<%= link_to "New target", new_target_path %>

app/views/targets/new.html.erb
<h1>New target</h1>

<%= render "form", target: @target %>

<br>

<div>
  <%= link_to "Back to targets", targets_path %>
</div>

app/views/targets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @target %>

<div>
  <%= link_to "Edit this target", edit_target_path(@target) %> |
  <%= link_to "Back to targets", targets_path %>

  <%= button_to "Destroy this target", @target, method: :delete %>
</div>