config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # namespace :admin do
  #     resources :targets
  #     resources :employees
  #     resources :teams
  #     resources :divisions
  #     resources :users
  #     root to: "users#index"
  #   end
  # devise_for :users
  resources :employees
  resources :divisions
  resources :targets
  resources :teams
  resources :users

  # root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/division.rb
class Division < ApplicationRecord
    has_one :Employee
    has_many :Team

    validates :name, presence:true
    validates :description, presence:true
    validates :teams, presence:true
    validates :manager, presence:true
end

app/controllers/admin/divisions_controller.rb
# module Admin
#   class DivisionsController < Admin::ApplicationController
#     # Overwrite any of the RESTful controller actions to implement custom behavior
#     # For example, you may want to send an email after a foo is updated.
#     #
#     # def update
#     #   super
#     #   send_foo_updated_email(requested_resource)
#     # end

#     # Override this method to specify custom lookup behavior.
#     # This will be used to set the resource for the `show`, `edit`, and `update`
#     # actions.
#     #
#     # def find_resource(param)
#     #   Foo.find_by!(slug: param)
#     # end

#     # The result of this lookup will be available as `requested_resource`

#     # Override this if you have certain roles that require a subset
#     # this will be used to set the records shown on the `index` action.
#     #
#     # def scoped_resource
#     #   if current_user.super_admin?
#     #     resource_class
#     #   else
#     #     resource_class.with_less_stuff
#     #   end
#     # end

#     # Override `resource_params` if you want to transform the submitted
#     # data before it's persisted. For example, the following would turn all
#     # empty values into nil values. It uses other APIs such as `resource_class`
#     # and `dashboard`:
#     #
#     # def resource_params
#     #   params.require(resource_class.model_name.param_key).
#     #     permit(dashboard.permitted_attributes).
#     #     transform_values { |value| value == "" ? nil : value }
#     # end

#     # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
#     # for more information
#   end
# end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: %i[ show edit update destroy ]

  # GET /divisions or /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1 or /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions or /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to division_url(@division), notice: "Division was successfully created." }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to division_url(@division), notice: "Division was successfully updated." }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url, notice: "Division was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def division_params
      params.require(:division).permit(:name, :description, :teams, :manager)
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_division.html.erb
<div id="<%= dom_id division %>">
  <p>
    <strong>Name:</strong>
    <%= division.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= division.description %>
  </p>

  <p>
    <strong>Teams:</strong>
    <%= division.teams %>
  </p>

  <p>
    <strong>Manager:</strong>
    <%= division.manager %>
  </p>

</div>

app/views/divisions/_form.html.erb
<%= form_with(model: division) do |form| %>
  <% if division.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
        <% division.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :teams, style: "display: block" %>
    <%= form.text_field :teams %>
  </div>

  <div>
    <%= form.label :manager, style: "display: block" %>
    <%= form.text_field :manager %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to "Show this division", @division %> |
  <%= link_to "Back to divisions", divisions_path %>
</div>

app/views/divisions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Divisions</h1>

<div id="divisions">
  <% @divisions.each do |division| %>
    <%= render division %>
    <p>
      <%= link_to "Show this division", division %>
    </p>
  <% end %>
</div>

<%= link_to "New division", new_division_path %>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to "Back to divisions", divisions_path %>
</div>

app/views/divisions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @division %>

<div>
  <%= link_to "Edit this division", edit_division_path(@division) %> |
  <%= link_to "Back to divisions", divisions_path %>

  <%= button_to "Destroy this division", @division, method: :delete %>
</div>